version: '3.7'

services:
  app:
    image: emqx/emqx
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
      # 挂载后文件权限不对，读取错误
    #    volumes:
    #      - "./conf/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf"
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"