version: '3.8'

services:
  postgres:
    container_name: postgres
    image: "postgres:9.6.22"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1123lovewm"
      PGDATA: "/data/postgres"
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped