version: '3.7'
services:
  qiandao:
    image: a76yyyy/qiandao:20211102
    container_name: qiandao
    restart: unless-stopped
    ports:
      - 12345:80
    volumes:
      - ./data:/usr/src/app/config
    tty: true
