version: "3.7"

services:
  jd:
    image: dreamacro/clash:latest
    container_name: clash
    restart: always
    tty: true
    ports:
      - "7890:7890"
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml