version: "3.7"

networks:
  heartzbeat:
    driver: bridge

services:
  hertzbeat-mysql:
    image: "mysql:5.7"
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./dbdata/mysqldata:/var/lib/mysql/
      - ./conf/sql:/docker-entrypoint-initdb.d/
    networks:
      - heartzbeat

  hertzbeat-TDengine:
    image: "tdengine/tdengine:2.4.0.12"
    container_name: tdengine
    hostname: tdengine
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6030-6049:6030-6049"
      - "6030-6049:6030-6049/udp"
    volumes:
      - ./dbdata/taosdata:/var/lib/taos/
    networks:
      - heartzbeat
