version: '3.7'
services:
  rabbit:
    image: rabbitmq:3.8.27-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data:/var/lib/rabbitmq