version: "3.7"

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data:/data"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=1123lovewm