version: "3.8"
services:
  torna:
    image: tanghc2020/torna:latest
    container_name: torna
    ports:
      - "7700:7700"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=192.168.2.49:3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=123456
    restart: unless-stopped